"""Browser smoke test for the public Streamlit deployment."""

from __future__ import annotations

import os

import pytest
from playwright.sync_api import Page, expect


PLACEHOLDER_URL = "PASTE_STREAMLIT_APP_URL_HERE"
DEPLOYED_APP_URL = (
    os.environ.get("STREAMLIT_APP_URL")
    or os.environ.get("DEPLOYED_STREAMLIT_APP_URL")
    or PLACEHOLDER_URL
).strip()
STREAMLIT_WAKE_TIMEOUT_MS = 120_000


def deployed_url() -> str:
    """Return the configured deployed Streamlit app URL or skip the smoke test."""
    if not DEPLOYED_APP_URL or DEPLOYED_APP_URL == PLACEHOLDER_URL:
        pytest.skip(
            "Set STREAMLIT_APP_URL to the deployed Streamlit app URL to run this "
            "public deployment smoke test."
        )
    return DEPLOYED_APP_URL


def test_deployed_streamlit_app_loads_without_visible_errors(page: Page) -> None:
    """Verify the deployed app opens without running heavy workflow actions."""
    page.goto(
        deployed_url(),
        wait_until="domcontentloaded",
        timeout=STREAMLIT_WAKE_TIMEOUT_MS,
    )

    expect(page.get_by_text("AI Molecule Design Assistant").first).to_be_visible(
        timeout=STREAMLIT_WAKE_TIMEOUT_MS
    )
    expect(page.get_by_text("generated by generative AI models").first).to_be_visible()
    expect(page.get_by_text("Guided example workflow").first).to_be_visible()

    visible_text = page.locator("body").inner_text(timeout=10_000)
    for error_text in (
        "Traceback",
        "streamlit.errors",
        "Uncaught app exception",
        "ModuleNotFoundError",
        "ImportError",
        "RuntimeError",
    ):
        assert error_text not in visible_text
